#!/usr/bin/env bash

set -e
pushd ~/.local/src/public/nixos
alejandra . &>/dev/null
git diff -U0 *.nix
echo "NixOS Rebuidling ... "
git add .
# sudo nixos-rebuild switch --flake "/home/zhenyu/.local/src/public/nixos/#nixuse" 2> nixos-switch.log || (
sudo nixos-rebuild -I nixos-config=configuration.nix switch --flake "/home/zhenyu/.local/src/public/nixos/#nixuse" 2> nixos-switch.log || (
# sudo nixos-rebuild -I nixos-config=configuration.nix switch 2> nixos-switch.log || (
	cat nixos-switch.log | rg error && git reset && false
)
gen=$(nixos-rebuild list-generations | grep current)
git commit -m "$gen"
git push origin master
popd
