#!/usr/bin/env bash

# set -e
# pushd ~/.local/src/public/nixos
pushd ~/.local/src/public/nixos-conf
alejandra . &>/dev/null
git diff -U0 *.nix
echo "NixOS Rebuidling ... "
git add .
# sudo nixos-rebuild switch --flake "/home/zhenyu/.local/src/public/nixos/#nixuse" 2> nixos-switch.log || (
sudo nixos-rebuild switch --flake ".#" || (git reset && false)
gen=$(nixos-rebuild list-generations --flake ".#" | grep current)
git commit -m "$gen"
git push origin master
popd
