#!/usr/bin/env bash

pushd ~/.local/src/public/nixos
alejandra . &>/dev/null
git diff -U0 *.nix
echo "NixOS Rebuidling ... "
# sudo nixos-rebuild -I nixos-config=configuration.nix switch --flake "/home/zhenyu/.local/src/public/nixos/#nixuse" 2> nixos-switch.log || (
sudo nixos-rebuild -I nixos-config=configuration.nix switch 2> nixos-switch.log || (
	cat nixos-switch.log | rg error && false
)
gen=$(nixos-rebuild list-generations | grep current)
git commit -am "$gen"
git push origin master
popd
