# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  boot.initrd.luks.devices = {
    crypted = {
      #device = "/dev/disk/by-uuid/3f14ceeb-fe2b-4360-974b-695004b8b640";
      device = "/dev/disk/by-partlabel/primary";
      preLVM = true;
      allowDiscards = true;
    };
  };
}
